//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTCGatewayAPI.Services {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BTCGatewayAPI.Services.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка добавления транзакции на отправку монет. Запрос: {0}.
        /// </summary>
        internal static string ErrAddOutputTransaction {
            get {
                return ResourceManager.GetString("ErrAddOutputTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обновления транзакции на отправку с id {0}.  Установка состояния &quot;Выполнено&quot; провалилась..
        /// </summary>
        internal static string ErrExceptionWhenChangingStateForOutputTx {
            get {
                return ResourceManager.GetString("ErrExceptionWhenChangingStateForOutputTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обновления транзакции на отправку с id {0}.  Переводим в состояние &quot;Выполнено&quot;....
        /// </summary>
        internal static string ErrExceptionWhenUpdateOutputTx {
            get {
                return ResourceManager.GetString("ErrExceptionWhenUpdateOutputTx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки транзакции на получение монет..
        /// </summary>
        internal static string ErrFailedToProcessIncomeTransactions {
            get {
                return ResourceManager.GetString("ErrFailedToProcessIncomeTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки транзакции на получение с txid {0}.
        /// </summary>
        internal static string ErrFailedToProcessInputTransactionWithTxId {
            get {
                return ResourceManager.GetString("ErrFailedToProcessInputTransactionWithTxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки транзакции на отправку.
        /// </summary>
        internal static string ErrFailedToProcessOutputTransaction {
            get {
                return ResourceManager.GetString("ErrFailedToProcessOutputTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки транзакции на отправку с txid {0}.
        /// </summary>
        internal static string ErrFailedToProcessOutputTransactionWithTxId {
            get {
                return ResourceManager.GetString("ErrFailedToProcessOutputTransactionWithTxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка получения последних обновлений..
        /// </summary>
        internal static string ErrGetLastUpdatesGeneralFail {
            get {
                return ResourceManager.GetString("ErrGetLastUpdatesGeneralFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка получения последних обновлений, пробуем еще раз....
        /// </summary>
        internal static string ErrGetLastUpdatesRetryAgain {
            get {
                return ResourceManager.GetString("ErrGetLastUpdatesRetryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сетевая ошибка.
        /// </summary>
        internal static string ErrNetworkingExceptionOccurs {
            get {
                return ResourceManager.GetString("ErrNetworkingExceptionOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Транзакция на отправку для кошелька с id: {0} не сохраняется. Запрос: {1}.
        /// </summary>
        internal static string ErrorSaveOutputTransaction {
            get {
                return ResourceManager.GetString("ErrorSaveOutputTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кошелек с id: {0} не обновляется. Запрос: {1}.
        /// </summary>
        internal static string ErrorUpdateWalletFails {
            get {
                return ResourceManager.GetString("ErrorUpdateWalletFails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операция не разрешена, попытка снятия несуществующей суммы..
        /// </summary>
        internal static string ErrTryToWithdrawMoreThanExcists {
            get {
                return ResourceManager.GetString("ErrTryToWithdrawMoreThanExcists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла необработанная ошибка.
        /// </summary>
        internal static string ErrUnhandledExceptionOccurs {
            get {
                return ResourceManager.GetString("ErrUnhandledExceptionOccurs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки кошелька с id: {0}.
        /// </summary>
        internal static string ErrUpdateWallet {
            get {
                return ResourceManager.GetString("ErrUpdateWallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обновления информации по кошельку, пробуем еще раз....
        /// </summary>
        internal static string ErrUpdateWalletInfo {
            get {
                return ResourceManager.GetString("ErrUpdateWalletInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обновления информации по кошельку, пробуем еще раз. Запрос: {0}.
        /// </summary>
        internal static string ErrUpdateWalletInformation {
            get {
                return ResourceManager.GetString("ErrUpdateWalletInformation", resourceCulture);
            }
        }
    }
}
